# Generated by Django 5.0.6 on 2024-09-06 10:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0015_alter_emergency_latitude_alter_emergency_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='case_number',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100),
        ),
    ]
