# Generated by Django 5.0.6 on 2024-09-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0016_emergency_case_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='case_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
