# Generated by Django 5.0.6 on 2024-09-23 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0018_user_phone_verified_user_verification_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_code_created_at',
        ),
    ]
